services:
  front-dev:
    container_name: front-dev
    build:
      context: frontend/
      target: dev
    env_file:
      - frontend/.env
    environment:
      - NODE_ENV=development
    ports:
      - "443:443"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles:
      - dev
  front-prod:
    container_name: front-prod
    build:
      context: frontend/
      target: prod
    env_file:
      - frontend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "443:443"
      - "80:80"
    profiles:
      - prod

  back-dev:
    container_name: back-dev
    build:
      context: backend/server/
      target: dev
    env_file:
      - backend/server/.env
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./backend/server:/app
      - /app/node_modules
      - ./backend/server/database:/app/database
    profiles:
      - dev
  back-prod:
    container_name: back-prod
    build:
      context: backend/server/
      target: prod
    env_file:
      - backend/server/.env
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    profiles:
      - prod
